provider "vault" {
  # $VAULT_ADDR should be configured with the endpoint where to reach Vault API.
  # Or uncomment and update following line
  # address = "https://vault.prod.yet.org"
  namespace = var.namespace
}

resource "vault_auth_backend" "approle" {
  depends_on = [vault_policy.terraform]
  type = "approle"
  path = var.approle_path
  description = "AppRole managed by Terraform"
  tune {
    default_lease_ttl = var.default_lease_ttl_seconds
    max_lease_ttl = var.max_lease_ttl_seconds
  }
}

resource "vault_approle_auth_backend_role" "terraform" {
  depends_on = [vault_policy.terraform]
  backend        = vault_auth_backend.approle.path
  role_name      = var.role_name
  token_policies = var.policies
}

resource "vault_approle_auth_backend_role_secret_id" "id" {
  backend   = var.approle_path
  role_name = var.role_name

  metadata = <<EOT
{
  "source": "Generated by Terraform Vault Provider"
}
EOT
  depends_on = [vault_approle_auth_backend_role.terraform]
}